# Generated by Django 3.2 on 2021-06-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comments',
        ),
    ]
