# Generated by Django 3.2 on 2021-06-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='post',
        ),
    ]
