# Generated by Django 3.2 on 2021-05-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210512_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image2',
            new_name='image_2',
        ),
    ]
